---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  linting:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@607b60294896f16c5ea3c37cdf5092a0021b56d4 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
