---
name: Manage issues on the projects board

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - uses: UCL-MIRSG/.github/actions/add-to-project@48c110143818699bc1aeee69a6296d00550fd950 # v0
        with:
          app-id: ${{ secrets.APP_ID }} # zizmor: ignore[secrets-outside-env]
          app-pem: ${{ secrets.APP_PEM }} # zizmor: ignore[secrets-outside-env]
